---
title: "Distribution of TPMs"
author: "Stefano Monti"
output:
  html_document:
    theme: united
    code_folding: show
    css: ../style/BS831.css
    toc: yes
    toc_float: no
    toc_depth: 4
---


```{r global, echo=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```

```{r settings}
## require() or library() statements
require(Biobase)
require(ggplot2)
require(BS831)
OMPATH <- Sys.getenv("OMPATH")
print(OMPATH)
```

## Load the Raw Count Data

```{r load.data}
data("HNSC_htseq_raw_counts_AEvsG1vsG3")
dge <- HNSC_htseq_raw_counts_AEvsG1vsG3
print(dim(dge))
```

## Transcripts Per Million (TPM)

We now transform into transcripts per million (TPM) according to the formula:

$$
TPM_{gene_i} =
\frac{\frac{Counts_{gene_i}}{Length_{gene_i}/1000}}{\sum_{i=1}^G\frac{Counts_{gene_i}}{Length_{gene_i}/1000}} \times 1E6
$$

Where $G$ is the total number of genes.

```{r tpm}
## retrieve transcript length information
len <- read.csv(file.path(Sys.getenv("OMPATH"),"data/GC_lengths_GRCh38.87.csv"),row.names=1)
cmn <- intersect(featureNames(dge),rownames(len))
len <- len[cmn,]
dge <- dge[cmn,]
if ( any(featureNames(dge)!=rownames(len)) ) stop( "featureNames(dge)!=rownames(len)" )

## Normalize expression by TPM
dgeTPM <- dge
## per 1000
len$KB <- len$Length/1000
## reads per transcript length (in KB)
expPKB <- apply( exprs(dgeTPM), 2, function(x){ x / len$KB } )
## Divide by total
exprs(dgeTPM) <- apply( expPKB, 2, function(x) { x / sum(x) * 1E6} )
## show
exprs(dgeTPM)[order(rowSums(exprs(dgeTPM)),decreasing=TRUE),][1:5,1:5]
```

### Library Sizes

Are all "library sizes" the same after TPM transformation?

```{r library.size}
lSize <- colSums(exprs(dgeTPM))
## are all sizes the same?
table(lSize)
```

## TPM's Median vs. MAD 
```{r med.vs.mad}
SS <- data.frame(
    MED=apply(exprs(dgeTPM),1,median),
    MAD=apply(exprs(dgeTPM),1,mad))
ggplot(SS,aes(MED,MAD)) +
    geom_point() +
    geom_smooth()
suppressWarnings(
ggplot(SS,aes(MED,MAD)) +
    geom_point() +
    geom_smooth() +
    scale_x_continuous(trans='log2') +
    scale_y_continuous(trans='log2'))
```

## Log2(TPM)'s Median vs. MAD 

```{r log2.med.vs.mad}
dgeTPMlog2 <- log2(exprs(dgeTPM)+1)
SS2 <- data.frame(
        MED=apply(dgeTPMlog2,1,median),
        MAD=apply(dgeTPMlog2,1,mad))
ggplot(SS2,aes(MED,MAD)) +
    geom_point() +
    geom_smooth()
```


